module.exports = {
    express: require("express"),
    path: require('path'),
    sharp: require("sharp"),
    puppeteer: require('puppeteer'),
    moment: require('moment'),
    crypto: require("crypto"),
    Razorpay: require('razorpay'),
    nodemailer: require("nodemailer"),
    multer: require("multer"),
    bcrypt: require("bcrypt"),
    jwt: require('jsonwebtoken'),
    session: require("express-session"),
    cookieParser: require("cookie-parser"),
    nocache: require("nocache"),
}
